services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: ankit_db
    volumes:
        - ./mysql_data_new:/var/lib/mysql
    networks:
        - two-tier
    ports:
        - "3306:3306"
          
          #above is for uses
          #below is for creation
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s 


    
    
  flask-app:
    build:
      context: .
    container_name: flask-app
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ankit_db
    networks:
      - two-tier
    ports:
      - "5000:5000"
        
    depends_on:
      - mysql
    restart: always




          
networks:
   two-tier:

volumes:
  mysql_data_new: 

        
